### ISSUE TITLE
Feature request: support running project version of tsc instead of global version

### ISSUE THREAD

**Issue by mmirus** [dmmulroy/tsc.nvim#1]
Hey there! Thanks for this plugin--could be a great enhancement for working with TypeScript in neovim!

Would it be possible to detect and use the current project's version of tsc before attempting to use a globally installed version?

I prefer to use project-local binaries for things like this wherever possible.

I was able to find a quick reference to how null-ls handles this for prettier, as an example:

- Key lines for prettier [one](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/prettier.lua#L39) and [two](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/prettier.lua#L45)
- Utilities used by the above [ref](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/920947793ce6e59616644cb4766d442121508bf3/lua/null-ls/helpers/command_resolver.lua#L29-L51)

**Comment by skdillon** [comment]
Hey thanks for the feedback and issue, you aren't the first to request this - it's heard and I'm planning on working on that early this week 🚀

**Comment by dmmulroy** [comment]
Hey thanks for the feedback and issue, you aren't the first to request this - it's heard and I'm planning on working on that early this week 🚀

**Comment by dmmulroy** [comment]
Hey @mmirus - the fix/feature should be merged into main and should work. Wanna give it a test run?

**Comment by mmirus** [comment]
It finds the local binary now. TY!

I did have this weird experience with the notifications, where it showed many of them instead of a single one that updates. I'll see if I can pinpoint anything in my config that causes it / a way to fix it, and if not I'll open a new issue.

![image](https://user-images.githubusercontent.com/524994/234317999-cc847ef7-6956-4002-b547-d0ccd84d0b1e.png)

Thank you again for for the quick work on this one!

**Comment by ecosse3** [comment]
@dmmulroy I have this issue now and I am unable to run `TSC` command in Neovim v0.10. 

```
.local/share/nvim/lazy/tsc.nvim/lua/tsc.lua:71: attempt to call field 'get_tsc_cmd' (a nil value)
```

**Comment by mmirus** [comment]
From a quick glance it looks like it can't find the `get_tsc_cmd` method from the utils module, not like it can't find the tsc binary. But you would think that if it has the new code that calls `get_tsc_cmd`, you would also have the new utils file. Maybe some weird caching thing or something? Just spitballing.

**Comment by ecosse3** [comment]
@mmirus @dmmulroy Yeah, that looks super weird. I reviewed code and it looks fine. Can it be an issue that in my nvim lua config I have file names `utils`? So it conflicts with plugin? I am not sure. After I reverted to previous commit it works again:

`lazy.nvim`
```lua
{
  "dmmulroy/tsc.nvim",
  cmd = "TSC",
  commit = "80c1839071443a7139cd8e1c93c6f78e35e5cf8f",
  config = true
},

```

**Comment by dmmulroy** [comment]
@mawkler's PR #8 hopefully resolves the utils issue. Try updating to `main` and see if that worked.

**Comment by mmirus** [comment]
Oh yeah, that could do it! :crossed_fingers:

**Comment by mmirus** [comment]
PS - this still works for me after pulling in the changes from #8.

**Comment by dmmulroy** [comment]
Super appreciative of all feedback, support, and help 🙏

**Comment by ecosse3** [comment]
@dmmulroy It works great now, thanks!
