### ISSUE TITLE
Running again should replace existing panel

### ISSUE THREAD

**Issue by sockthedev** [dmmulroy/tsc.nvim#11]
Thanks for the update to use the local `tsc` install! Works well. :)

I've noticed that if I run `:TSC`, fix some changes, then run the `:TSC` command again, the panel doesn't update to show the reduced error list. I have to close the panel first, and then run `:TSC`.

**Comment by dmmulroy** [comment]
Ope sorry about that, I'll take a look and try to get a fix in this evening. Thanks for the issue.

**Comment by dmmulroy** [comment]
@sockthedev I was able to rerun `:TSC` after fixing a subset of errors and see the list update so I couldn't reproduce your exact issue, but I did find that if you run `:TSC`once and get errors, fix them, and then run it again, the list wouldn't clear.

**Comment by sockthedev** [comment]
@dmmulroy the plugin is working amazing! thanks so much. it's an integrated part of my flow now. so convenient. 💜
