### ISSUE TITLE
Bug: tsc.nvim not working in monorepos

### ISSUE THREAD

**Issue by skdillon** [dmmulroy/tsc.nvim#16]

**Comment by carlosflorencio** [comment]
Was also testing the plugin, doesn't seem to work with npm monorepos as well. 

Example folder structure:
```
npm-monorepo/
├── node_modules
├── apps/
│   └── web/
│       ├── package.json
│       └── tsconfig.json
├── packages/
│   └── shared-lib/
│       ├── package.json
│       └── tsconfig.json
└── package.json
```

Currently says it doesn't find any errors when running TSC but it doesn't run the tsc in the right folder.

**Comment by dmmulroy** [comment]
Thanks for the comment and info! This will be helpful for debugging

**Comment by dmmulroy** [comment]
@carlosflorencio Could you try using the following config:

```lua
require("tsc").setup({
  flags = "--build",
})
```

**Comment by carlosflorencio** [comment]
@dmmulroy yep, using the `--build` flag with [Typescript Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) inside a `tsconfig.json` in the root folder works :).

**Comment by carlosflorencio** [comment]
It would be cool to have a config option where we could override the default cwd the command runs, e.g I'd like to have the possibility of running `tsc` in the closest folder that has a `tsconfig.json` file from the current open buffer 💪.

**Comment by skdillon** [comment]
Sweet glad there's a temporary workaround. As far the config option, that's kind of where my head was going as well - I'll draft up a PR for that over the next day or two and tag you in it for review/feedback if you're interested.

**Comment by dmmulroy** [comment]
@carlosflorencio PR is up 🎉

**Comment by carlosflorencio** [comment]
@dmmulroy awesome! Works now without need to setup the `--build` 🎉.

But I found one issue, the quickfix list is using the file paths returned from the `tsc` output, but in the monorepo setup, that path is relative to the closest folder with the `tsconfig.json` file and thus it doesn't work.

e.g:
```
npm-monorepo/
├── node_modules
├── apps/
│   └── web/
│       ├── package.json
│       └── tsconfig.json
├── packages/
│   └── shared-lib/
│       ├── package.json
│       └── tsconfig.json
└── package.json
``` 

`neovim` is opened in the `npm-monorepo` path, when editing a file under `apps/web/subfolder/index.ts` and running `:TSC`, the quickfix (in case of errors) will have the path `subfolder/index.ts` instead of `apps/web/subfolder/index.ts`.

**Comment by dmmulroy** [comment]
![ahh-curses-skeletor](https://user-images.githubusercontent.com/2755722/236492775-5ae0a3a7-b6e9-45b8-9cce-6320543b09fe.gif)

**Comment by dmmulroy** [comment]
Will open a PR tonight to fix 😄

**Comment by carlosflorencio** [comment]
![giphy](https://user-images.githubusercontent.com/1500881/236493348-e33fd02c-547b-442d-8b96-f7366588ef67.gif)

**Comment by skdillon** [comment]
@carlosflorencio could you upload a sample repo with that file structure?

**Comment by dmmulroy** [comment]
Made some updates and hoping I've got it nailed down now - @carlosflorencio want to update and give it a spin?

**Comment by carlosflorencio** [comment]
It's perfect now @dmmulroy, thanks a lot for your effort! 🚀 💪
