### ISSUE TITLE
Errors with LazyVim nvim-notify configuration

### ISSUE THREAD

**Issue by phaalonso** [dmmulroy/tsc.nvim#17]
I just installed tsc.nvim, and tried to run it but it spamming nvim-notify errors. Even when the project has erros, nothing is being reported
[Gravação de tela de 2023-05-02 20-01-57.webm](https://user-images.githubusercontent.com/26033899/235803661-ed93f9e7-2364-40ab-b591-ee40c150a25e.webm)

[My config](https://github.com/phaalonso/dotfiles/blob/master/nvim/lua/plugins/completion.lua)

**Comment by dmmulroy** [comment]
Hey @phaalonso, thanks for the issue and sorry you're having this problem. I suspect it's because when vim.notify is overwritten it needs to return the record from notify.nvim. I'm taking a look now.

**Comment by dmmulroy** [comment]
Okay, could you try overriding the default `nvim-notify` that ships with `LazyVim` (found here: https://www.lazyvim.org/plugins/ui#nvim-notify)

and modify the `init` option to be just:

```lua
function()
  vim.notify = require("notify")
```

**Comment by phaalonso** [comment]
Same problem as before:
![image](https://user-images.githubusercontent.com/26033899/236105812-9c1bfa22-6e1c-474a-95da-02f0d2c27329.png)

Configs:
![image](https://user-images.githubusercontent.com/26033899/236105856-12f2f362-5ac7-4131-b9c1-33d8309c0dc9.png)

**Comment by phaalonso** [comment]
There is some progress :D 

Now the notifications appears, but errors in the project aren't being reported

[Gravação de tela de 2023-05-04 00-30-09.webm](https://user-images.githubusercontent.com/26033899/236106969-062860d3-9efb-494a-b60b-15ef8abed77e.webm)

**Comment by skdillon** [comment]
The notifications shouldn't be appearing like that, they should be replacing a single one. I'm going to have to dig into lazyvim, they do some weird stuff w/ notify: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/init.lua#L162-L197

As far as it not reporting issues, that's a bit strange - is the repo you're working in using any sort of monorepo tech? Could you create a repo the recreates the issue that I could clone?

**Comment by phaalonso** [comment]
It's not a monorepo. I will try to run in others projects to see if the problem persists

**Comment by phaalonso** [comment]
Yesterday I updated my plugins, and now it's reporting the erros. But the notification error are still happening

**Comment by dmmulroy** [comment]
It's not a great solution, but I can resolve this you can setup `tsc.nvim` with these options, it unfortunately will partially disable the UI, but you'll still be able to type check your project. I'm going to open an issue w/ LazyVim to try and get some help understanding what's going on and how to fix resolve it.

```lua
require('tsc').setup({
   enable_progress_notifications = false
 })
 ```
