### ISSUE TITLE
qflist sending to empty buffers

### ISSUE THREAD

**Issue by NiloDrumond** [dmmulroy/tsc.nvim#19]
When I try to open the file on qflist I get sent to an empty buffer.

The type errors are captured as expected, but you can even see on the preview that the file is empty
![image](https://user-images.githubusercontent.com/48765760/236562442-79b26a11-6ef7-49a1-990f-e33aa00b612a.png)

If I press enter in any of the files, I get sent to an empty buffer:
![image](https://user-images.githubusercontent.com/48765760/236562596-3234cc7c-74a2-4975-a616-647716c2cfac.png)

Additional info:
- The project is a simple Next.js project that doesn't use a src folder.
- I'm using the default configs of the plugin
- The tsconfig file:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./*"
      ]
    },
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by skdillon** [comment]
Thanks for the issue - I was able to reproduce this will have a fix up shortly.

**Comment by skdillon** [comment]
@NiloDrumond Fix should be in - lmk if you're still having problems.
