### ISSUE TITLE
Sends new toast instead of updating ?

### ISSUE THREAD

**Issue by bogdan-calapod** [dmmulroy/tsc.nvim#2]
Hello and thank you for this interesting project - just one step closer to VSCode feature parity :D 

I've tried the plugin and it does work great, but with one small issue - it seems that it sends multiple `nvim-notify` notifications instead of updating the one.

I'm using a setup based on [ecovim](https://github.com/ecosse3/nvim/), so I don't think there's anything I've done which broke things. My setup is available at [nvim-dotfiles](https://github.com/bogdan-calapod/nvim-dotfiles). 

I'm pretty new to Vim and don't know exactly how to debug this, although I do have a basic understanding of the pieces involved in the setup. I do see that [updating notifications should be possible](https://github.com/rcarriga/nvim-notify/issues/43).

The notifications look like this:

![image](https://user-images.githubusercontent.com/5462727/234188024-91a09758-8638-442d-9a69-d63cfb537fbd.png)

Thanks again!

**Comment by mawkler** [comment]
I'm seeing the same behaviour

**Comment by dmmulroy** [comment]
You see I do something similar in my own dotfiles/configuration of `nvim-notify` (https://github.com/dmmulroy/dotfiles/blob/main/.config/nvim/after/plugin/nvim_notify.lua#L7-L14)

```lua
vim.notify = function(message, level, opts)
  for _, msg in ipairs(filtered_message) do
    if message == msg then
      return
    end
  end
  return notify(message, level, opts)
end
```

**Comment by bogdan-calapod** [comment]
That fixed it, thanks a lot!

**Comment by dmmulroy** [comment]
Awesome - the new PR is also up here https://github.com/ecosse3/nvim/pull/133 if you'd like to add any input.

**Comment by mawkler** [comment]
I'm having the same issue with this minimal lazy.nvim configuration:

```lua
{ 'dmmulroy/tsc.nvim', config = true },
{
  'rcarriga/nvim-notify',
  config = function()
    vim.notify = require('notify')
  end
}
```

This is what `:Notifications` looks like after I've run `:TSC` with the config above:

![image](https://user-images.githubusercontent.com/15816726/234293524-50c799b8-607c-4a5d-88f3-f591a9894e5d.png)

**Comment by mmirus** [comment]
Beautiful. Adding that `return` fixed this problem for me. Thank you!

**Comment by mmirus** [comment]
@mawkler Most likely the [`hide_from_history` ](https://github.com/rcarriga/nvim-notify/blob/master/doc/nvim-notify.txt#L52)option needs to be added to the notification options. https://github.com/dmmulroy/tsc.nvim/blob/main/lua/tsc/init.lua#L95

**Comment by mawkler** [comment]
@mmirus That solves it! I've created a PR: #10

**Comment by mmirus** [comment]
> @mmirus That solves it! I've created a PR: #10

Awesome!
