### ISSUE TITLE
vue-tsc or tsc binary path option support

### ISSUE THREAD

**Issue by dLedda** [dmmulroy/tsc.nvim#26]
Hi, thanks for this plugin, I've found it very useful. 
I use Vue at work and privately as well and vue-tsc is the go-to typechecker, as it also parses the .vue files into typecheckable TypeScript. I would be grateful if you could also include the command name as an option (i.e. `npx vue-tsc` in this case) to override the default behaviour, or an option to include the path to binary (I see that this would probably be the easiest option)? As far as I am aware the interface and console output are the same.

**Comment by dmmulroy** [comment]
Hey thanks for the issue! I'd be down to add `bin_path` as a config option. I can try and get around to this later this week some morning, or if you'd like you can feel free to submit a PR in the interim. :)

**Comment by dLedda** [comment]
No problem, thanks for considering. No hurry at all. :) 
I might have a look myself if I have some free time, although I am not particularly well versed in lua or the (Neo)vim API, just enough to cobble together the configs.

**Comment by dmmulroy** [comment]
@dLedda This should be good to go! Lmk if you hit any gotchas after upgrading

**Comment by dLedda** [comment]
Hey, thanks so much for doing this! It works great! Will enjoy using this at work.
