### ISSUE TITLE
Add callback to qflist opened

### ISSUE THREAD

**Issue by benfc1993** [dmmulroy/tsc.nvim#43]
Hi, Just wondering if supporting something like this would be possible. I am using Trouble for Diagnostics, quickfix etc.

Currently I am using an autocmd to hook into when the quickfix list is opened to swap to using trouble:
```lua
vim.api.nvim_create_augroup("trouble-quickfix", { clear = true })
vim.api.nvim_create_autocmd({ "BufWinEnter" }, {
	group = "trouble-quickfix",
	callback = function()
		if vim.bo.buftype == "quickfix" then
			print(#(vim.fn.getqflist()))
			if #(vim.fn.getqflist()) > 0 then
				vim.schedule(function()
					vim.cmd("Trouble quickfix")
				end)
				vim.schedule(function()
					vim.cmd("ccl")
				end)
			else
				vim.schedule(function()
					vim.cmd("TroubleClose")
				end)
			end
		end
	end,
})
``` 

However this does mean this behaviour isn't scoped to just tsc errors. Would it be possible to expose an `on_qflist_open` callback to allow scoping this kind of behaviour?

Happy to make a PR if this would be of interest

Cheers

**Comment by benfc1993** [comment]
Happy to have a look into it, although I don't know if you'd want to make trouble a dependancy. I guess it could be an optional dep, with an option to use it for qf. Kind of how you allow for notify?

**Comment by dmmulroy** [comment]
That could be an option - I don't know enough about Trouble yet to have a well thought opinion on it yet.

**Comment by benfc1993** [comment]
Code is ready to go all working really well, I can't push as I don't have permissions would you be able to grant me perms please.

**Comment by dmmulroy** [comment]
Awesome, thank you for your time and effort! Could you please create a fork and open a PR that way 🙏

**Comment by benfc1993** [comment]
PR raised 😃 #44

**Comment by dmmulroy** [comment]
Cloed by #44
