### ISSUE TITLE
suport tsc-absolute

### ISSUE THREAD

**Issue by zodman** [dmmulroy/tsc.nvim#58]
tsc-absolute its a wrapper of tsc ...

```
npx -y -p tsc-absolute -p typescript@<version.x.x> tsc-absolute --pretty --noEmit -p <directory>
```

With a monorepo with a lot of directory its very useful and give you the complete full path of the file problem

**Comment by zodman** [comment]
I didnt see it amazing>!!

**Comment by dmmulroy** [comment]
Awesome, enjoy!
