### ISSUE TITLE
Lazyvim updated to Snacks.notifier causing the loader to spam notifications

### ISSUE THREAD

**Issue by AlexBeauchemin** [dmmulroy/tsc.nvim#59]
Lazyvim moved from nvim-notify to Snacks.notifier for notifications, which seems to have caused a side effect of displaying a new notification for every state of the loader instead of updating the existing one (see screenshot)

Doesn't break anything, just slightly annoying visually

![image](https://github.com/user-attachments/assets/cf9ad4cf-2a94-46b7-a125-14b38702b40d)

**Comment by AlexBeauchemin** [comment]
Create a pull request here: https://github.com/dmmulroy/tsc.nvim/pull/60

**Comment by dmmulroy** [comment]
Resolved - thanks y'all. Had no idea this was happening.
