### ISSUE TITLE
Feature Request: Add configuration option to prevent qflist for automatically opening

### ISSUE THREAD

**Issue by dmmulroy** [dmmulroy/tsc.nvim#6]
![image](https://user-images.githubusercontent.com/2755722/234305289-0cef8b38-9213-4dd2-8e4d-96c8fcc25651.png)

**Comment by mmirus** [comment]
Whether as an alternative to implementing this option, or as a workaround until it's implemented, it's possible to automatically close the QF list and open it in trouble instead. Ref.: https://github.com/folke/trouble.nvim/issues/70#issuecomment-1522085016

**Comment by dmmulroy** [comment]
Hey @mmirus, I merged in a configuration option, `auto_open_qflist`, tonight (#13) - hopefully it helps!
