### ISSUE TITLE
Feature Request: Pretty TS Errors

### ISSUE THREAD

**Issue by dmmulroy** [dmmulroy/tsc.nvim#7]
Context: https://www.reddit.com/r/neovim/comments/12q7atv/pretty_errors_plugin_like_this/

**Comment by sockthedev** [comment]
Holy smokes would love this.

**Comment by princejoogie** [comment]
i found a similar one that i use -> https://github.com/davidosomething/format-ts-errors.nvim
![image](https://github.com/dmmulroy/tsc.nvim/assets/47204120/dc086a1e-a855-43bb-81a7-11eda524dc9d)

**Comment by dmmulroy** [comment]
Thanks for the link! I'm not sure that particular plugin would be useful as it appears to mostly be handling formatting/indenting and wouldn't be very impactful for the message in the qflist (the one place we have to work with). I think if this were to be a feature I'd need to translate Matt Pocok's https://github.com/mattpocock/ts-error-translator/tree/main/packages/engine to lua and use that.

**Comment by akinsho** [comment]
Drive by comment: I don't think you'd have to rewrite that project in lua, you could use something like https://github.com/TypeScriptToLua/TypeScriptToLua and just transpile the final result to lua

**Comment by pmwals09** [comment]
Is this still open to work on? I was playing around with it tonight and think I've got something going.

Would this need to be a configurable option, or should these "nice" messages just replace the existing ones from the compiler? I would still include the "TS####" portion.

The "nice" messages at the repo linked above include markdown links - as far as I know we can't have a clickable link in the qflist so I was planning to parse them out, but lmk if I'm unaware of some feature there.

**Comment by dmmulroy** [comment]
@pmwals09 Awesome yeah this definitely still needs work. I think I would like to add a top level "prettify" config option to turn it on or off.

**Comment by dmmulroy** [comment]
Resolved by #32 - thanks @pmwals09!
